const colors = {
  primary: "#449514",
  primary_accent: "#97DD27",
  secondary: "#C3EFA9D4",
  yankees_blue: "#1D2939",
  gray: "#98A1B5",
  auro_metal_saurus: "#667085",
  cadet_grey: "#98A1B5",
  bright_grey: "#EAECF0",
  ghost_white: "#F9FAFB",
  red: "#F51E1E",
  green : "#219E38",
  charcol: "#37474F",
  acid_green: "#BDCC13",
  blue: "#3D3AA9",
  white: "#FFFFFF",
  black: "#000000",
  pale_spring_bud: "#EDF7B5",
  transparent: "rgba(255,255,255,0)",
  pale_pink: "#FDCBE9",
};

const colorNames = [
  "primary",
  "primary_accent",
  "secondary",
  "yankees_blue",
  "gray",
  "auro_metal_saurus",
  "cadet_grey",
  "bright_grey",
  "ghost_white",
  "red",
  "green",
  "charcol",
  "acid_green",
  "blue",
  "white",
  "black",
  "pale_spring_bud",
  "transparent",
];

export { colors, colorNames };
